// Regenerates supabase/seed.sql from ../seed/board.json and ../seed/survey_1500_gateway.json,
// the same seed content the artifact prototype was loaded with.
// Usage: node scripts/generate-seed.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const seedDir = join(here, '..', '..', 'seed');
const { board, cards } = JSON.parse(readFileSync(join(seedDir, 'board.json'), 'utf8'));
const survey = JSON.parse(readFileSync(join(seedDir, 'survey_1500_gateway.json'), 'utf8'));

const q = v => (v == null || v === '' ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const qs = v => `'${String(v ?? '').replace(/'/g, "''")}'`;
const j = v => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;

const out = [
  '-- Generated by scripts/generate-seed.mjs. Do not edit by hand.',
  `insert into public.boards (id, title, subtitle, framing) values (${q(board.id)}, ${q(board.title)}, ${q(board.subtitle)}, ${q(board.framing)}) on conflict (id) do nothing;`,
  '',
];
const perCol = {};
for (const c of cards) {
  perCol[c.col] = (perCol[c.col] || 0) + 1;
  out.push(`insert into public.cards (board_id, n, title, col, ord, description, verdict, breaks, track, survey_tactic, created_by) values (${q(board.id)}, ${c.n}, ${q(c.title)}, ${q(c.col)}, ${perCol[c.col] * 1000}, ${qs(c.description)}, ${qs(c.verdict)}, ${qs(c.breaks)}, ${q(c.track)}, ${q(c.survey_tactic)}, null);`);
}
out.push('',
  `insert into public.surveys (id, board_id, title, respondents, note, tactics, responses, takeaways) values ('gateway1500', ${q(board.id)}, ${q(survey.title)}, ${survey.respondents}, ${q(survey.note)}, ${j(survey.tactics)}, ${j(survey.responses)}, ${j(survey.takeaways)}) on conflict (id) do nothing;`);
writeFileSync(join(here, '..', 'supabase', 'seed.sql'), out.join('\n') + '\n');
console.log(`Wrote ${cards.length} cards to supabase/seed.sql`);
